Feature/MockViewController + Coordinator 구현
boostcampwm-2022/iOS02-Trinap pull request #146
Opened 2022-11-19 12:54 UTC by ByeongjooYoo

# 작업 내용
> 해결한 이슈 넘버와 설명을 적어주세요

resolved: #67

# 질문 및 특이사항
> 해결하지 못한 부분이나 팀원들에게 알려줄 사항을 적어주세요
임시로 MockViewController로 Coordinator Flow를 구현하였습니다.
해당 ViewController는 UI구현 후 교체 해주세요!
TabBar에 들어가는 image 중 사이즈가 맞지 않는 image를 교체하였습니다.

# 체크리스트
- [ ] 빌드가 되는 코드인가요?
- [ ] Warning이 없는 코드인가요?
- [ ] Merge할 브랜치가 올바른가요?
- [ ] 코딩 컨벤션이 올바른가요?

2022-11-19 13:41 UTC, d0yvn approved these changes

2022-11-19 13:41 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/Coordinator/TabBarPageCase.swift
> +    }
enum에 Int 타입 채택하면 위 과정을 생략할 수 있지 않을까요?

2022-11-19 13:52 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/Coordinator/TabBarPageCase.swift
> +    }
오! 수정해두겠습니다~!

2022-11-19 13:58 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/Coordinator/TabBarPageCase.swift
> +    }
이 과정은 도윤님이 말씀하신데로 rawValue로 수정 해두겠습니다!
하지만 `TabBarCoordinator`에서 `TabBarPageCase`를 생성할 때  t`abBarController.selectedIndex`로 생성하기 때문에 init은 저렇게 가는게 맞는것 같습니다!

2022-11-19 14:03 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/Coordinator/TabBarPageCase.swift
> +    }
수정해두겠습니다! 👍

2022-11-20 06:29 UTC, yy0867 requested changes

2022-11-20 06:29 UTC, yy0867 commented on Trinap/Sources/App/AppCoordinator.swift
> +    func connectTaBarFlow() {
오타 있습니다!

2022-11-20 06:29 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Coordinator/TabBarPageCase.swift
> +enum TabBarPageCase: Int, CaseIterable {
TabBarPage나 TabBarPageType은 어떠신가요?

2022-11-20 06:29 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Coordinator/TabBarPageCase.swift
> +    func selectedTabIcon() -> UIImage {
`pageOrderNumber`, `pageTitle`, `tabIcon`, `selectedTabIcon` 모두
하나의 case에 대한 속성이므로 이름이 조금 간단하면 좋을 것 같습니다!

`index`, `title`, `icon`, `selectedIcon` 같은 느낌입니닷

그리고 프로퍼티와 함수를 섞어서 사용한 이유가 있으실까요?

2022-11-20 06:29 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/Coordinator/MainCoordinator.swift
> +        let viewController = MockPhotographerListViewController()
👍

2022-11-20 06:29 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Coordinator/TabBarPageCase.swift
> +enum TabBarPageCase: Int, CaseIterable {
해당 enum에 'tabBarItem' 프로퍼티를 하나만 두고, 거기서 UITabBarItem을 만들어서 반환하는것은 어떨까요?

2022-11-20 11:54 UTC, ByeongjooYoo commented on Trinap/Sources/App/AppCoordinator.swift
> +    func connectTaBarFlow() {
수정해두겠습니다~!

2022-11-20 11:55 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/Coordinator/TabBarPageCase.swift
> +    func selectedTabIcon() -> UIImage {
딱히 이유는 없습니다.... 하나로 통일하여 수정한다면 `프로퍼티`와 `함수` 중 어느 것으로 사용하는게 좋을까요?

2022-11-20 12:11 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Coordinator/TabBarPageCase.swift
> +    func selectedTabIcon() -> UIImage {
https://github.com/boostcampwm-2022/iOS02-Trinap/pull/146#discussion_r1027233211

이 방법으로 하면 프로퍼티나 함수 모두 없앨 수 있지 않을까요?!

2022-11-21 02:32 UTC, yy0867 approved these changes
고생하셨습니다 !

2022-11-21 02:32 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Coordinator/TabBarPageType.swift
> +    var tabBarItem: UITabBarItem {
👏

2022-11-21 02:32 UTC, merged