Feature/edit detail photograhper
boostcampwm-2022/iOS02-Trinap pull request #182
Opened 2022-11-27 11:46 UTC by d0yvn

# 작업 내용
> 해결한 이슈 넘버와 설명을 적어주세요

- EditPhotographerViewModel 구현 #56 삭제에 대한 세부동작 구현 필요
- resolved: #31 

# 질문 및 특이사항
> 해결하지 못한 부분이나 팀원들에게 알려줄 사항을 적어주세요

UI구현 및 데이터 불러오는 것 까지 구현했습니다.
사진 삭제에 대한 기능 구현 필요.

# 체크리스트
- [x] 빌드가 되는 코드인가요?
- [ ] Warning이 없는 코드인가요?
- [x] Merge할 브랜치가 올바른가요?
- [x] 코딩 컨벤션이 올바른가요?

2022-11-27 12:03 UTC, yy0867 commented on Trinap/Sources/Data/Repositories/Photograhper/DefaultPhotograhperRepository.swift
> +        .compactMap { $0[0].toObject(PhotographerDTO.self)?.toModel() }
`$0.first?.toObject...`는 어떨까요?!

2022-11-27 12:03 UTC, yy0867 commented on Trinap/Sources/Presenter/Common/Base/BaseCollectionReusableView.swift
> +    @objc optional func didTapButton()
어떤 동작에 관한 메서드인가요?

Cell 안에 버튼이 있을 때 해당 버튼에 `~~.rx.tap`을 사용했을 때랑
아래의 `rxTap`이랑의 차이점이 궁금합니다!

2022-11-27 12:03 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/ColletionView/PhotographerReivewCell.swift
> +    override func configureAttributes() {
사용할 일이 없다면 제거하는 것도 좋을 것 같습니다!

2022-11-27 12:03 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPhotographerViewModel.swift
> +                                }
내부 로직들을 따로 메서드로 빼고, flatMap 안에서 해당 메서드를 호출하면 가독성이 조금 더 좋아질 것 같습니다..!

2022-11-27 12:03 UTC, yy0867 commented on TrinapTests/Sources/UseCase/Review/FetchReviewUseCaseTests.swift
> +            .createHotObservable([
HotObservable로 호출하신 이유가 궁금합니다..!

2022-11-27 12:03 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/ColletionView/EditPhotographerPhotoHeaderView.swift
> +                self?.delegate?.didTapButton?()
혹시 Delegate를 호출하신 이유가 Proxy에서 해당 Observable을 트리거하기 위한 호출인가요?
Proxy를 위한 Delegate를 뷰에서 호출하는 것 같아서 여쭤봅니다..!

2022-11-27 12:04 UTC, chansooo requested changes
PhotographerSection은 UI를 구성할 때 사용하는 diffableDataSource를 사용할 때 사용하려고 만드신 것 같은데 이 부분과 각각의 모델의 toDataSource라는 함수들이 data layer에 있는 것이 맞는지 궁금합니다! 
계층을 나눠서 사용하는 이유 중 하나가 더 코어한 레이어가 다른 레이어에 간섭을 받지 않아야 하는데 현재처럼 진행하게 되면 뷰나 data가 바뀌게 되면 domain layer까지 바꿔줘야 하는 경우가 생길 수도 있을 것 같아요.

따로 presenter layer에 mapper와 같은 아이들을 만드는 게 나을 수도 있을 것 같습니다.

또한 현재 저를 포함한 모두가 몇가지 기본적으로 있던 모델들을 조합해서 뷰모델에서 사용되는 모델을 만들었는데 (예를 들어 제가 만든 photographerPreview) 해당 구조체들이 Domain layer에 들어가는게 맞는지 점점 혼돈이 오네요... 사실 photographerPreview도 photographer와 review의 인자들을 합쳐서 만든 아이들이니,,,,

내일 다 같이 한번 이야기해보면 좋을 것 같아요 :)

2022-11-27 12:04 UTC, chansooo commented on TrinapTests/Sources/UseCase/Review/FetchReviewUseCaseTests.swift
>      }
👍

2022-11-27 12:04 UTC, yy0867 commented
저번에 그 에러는 바로 찾으셨나요..? ㅋㅋㅋㅋㅋㅋ

2022-11-27 12:07 UTC, yy0867 requested changes
`EditPhotographerDataSourceAdapter(?)`같은 클래스를 만들어서
뷰모델이 데이터를 가공할 때 해당 클래스를 사용하도록 하는 구조는 어떨까요..?

2022-11-27 13:46 UTC, d0yvn commented on Trinap/Sources/Presenter/Common/Base/BaseCollectionReusableView.swift
> +    @objc optional func didTapButton()
동작 차이는 없는데 private로 버튼에 접근 못하게 하려고 했었는데 사실 Proxy가 무의미해보이네요! 수정하겠습니다.

2022-11-27 13:57 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/ColletionView/EditPhotographerPhotoHeaderView.swift
> +                self?.delegate?.didTapButton?()
rxTap으로 구현해둔 메서드가 delegate.didTap될때 동작하는 방식으로 구현했었는데 불필요한 로직인 것 같아서 삭제하겠습니다!

2022-11-29 04:21 UTC, ByeongjooYoo approved these changes

2022-11-29 04:21 UTC, ByeongjooYoo commented on Trinap/Sources/Domain/UseCases/Photographer/DefaultFetchPhotographerUseCase.swift
>      }
photographerRespository.fetchDetailPhotographer(userId: photographerId)에서 userId로 `photographer` 정보를 요청한다면 `fetch(photographerId: String)` -> `fetch(photographerUserId: String)`로 변경되면 좋을 것 같습니다!
userId인지 document의 Id를 원하는 건지 혼동이 올 수 있을 것 같아요!

2022-11-29 04:27 UTC, chansooo approved these changes
👍

2022-11-29 04:27 UTC, chansooo commented on Trinap/Sources/Domain/UseCases/Review/DefaultFetchReviewUseCase.swift
>      }
first(where:) 메소드 사용하면 이중 for문 더 예쁘게 처리할 수 있지 않을가요?

2022-11-29 04:27 UTC, chansooo commented on Trinap/Sources/Domain/UseCases/Review/DefaultFetchReviewUseCase.swift
> +    }
👍

2022-11-29 04:27 UTC, chansooo commented on Trinap/Sources/Presenter/Common/Base/BaseCollectionViewCell.swift
var로 바꾸신 이유가 궁금합니다!

2022-11-29 04:27 UTC, yy0867 approved these changes

2022-11-29 04:27 UTC, yy0867 commented on Trinap/Sources/Domain/Models/Photographer/PhotographerPreview.swift
> +    init(
👍

2022-11-29 04:27 UTC, yy0867 commented on Trinap/Sources/Domain/Models/Photographer/PhotographerUser.swift
> +        self.pictures = [nil] + photographer.pictures.map { url in
`nil`을 추가하는 이유가 + 버튼 때문인가요?

2022-11-29 04:27 UTC, yy0867 commented on Trinap/Sources/Domain/UseCases/Review/DefaultFetchReviewUseCase.swift
> +//    }
?!

2022-11-29 04:27 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPhotographerViewController.swift
> +                cell.isUserInteractionEnabled = false
이 부분 전체 `switch`문 안에서 로직이 각 case별로 중복되는 것 같은데,
제네릭으로 작동하는 메서드를 만들고 각 case에서 해당 메서드만 호출시키는 방법도 좋을 것 같습니다!

2022-11-29 04:29 UTC, d0yvn commented on Trinap/Sources/Domain/Models/Photographer/PhotographerUser.swift
> +        self.pictures = [nil] + photographer.pictures.map { url in
넵

2022-11-29 04:33 UTC, d0yvn commented on Trinap/Sources/Presenter/Common/Base/BaseCollectionViewCell.swift
ViewController에서 cell 내부의 rx.tap을 했을 때 버튼이 연속으로 두번 눌리는 버그가 있어서 prepareForReuse할때 disposeBag을 새로 업데이트 시켜줬습니다!

2022-11-29 04:39 UTC, d0yvn commented on Trinap/Sources/Domain/UseCases/Review/DefaultFetchReviewUseCase.swift
> +//    }
확실하지 않은 내용이라서 주석처리해놓았습니다. 리뷰 부분 구현할 때 필요하지 않는다면 삭제하겠습니다.

2022-11-29 04:45 UTC, merged