Feature/SelectReservationDateView 구현
boostcampwm-2022/iOS02-Trinap pull request #184
Opened 2022-11-27 12:33 UTC by ByeongjooYoo

# 작업 내용
> 해결한 이슈 넘버와 설명을 적어주세요

- #14 
- #43 

# 질문 및 특이사항
> 해결하지 못한 부분이나 팀원들에게 알려줄 사항을 적어주세요
- SelectReservationDateView가 dismiss 될 때 선택한 날짜를 어떻게 전달해야 하는지 고민 중이라 해당 부분은 아직 미구현 되었습니다.
- 예약 가능한 시간이 없는 경우 UI 처리가 빠져 있습니다.
- SelectReservationDateView에서 작가의 영업가능한 날짜를 받아와야 합니다. 해당 데이터는 `photographerId`를 주입받아서 해당 id로 작가 영업일을 직접 받아오려고 하는데 어떻게 생각하시나요?

# 체크리스트
- [ ] 빌드가 되는 코드인가요?
- [ ] Warning이 없는 코드인가요?
- [ ] Merge할 브랜치가 올바른가요?
- [ ] 코딩 컨벤션이 올바른가요?

2022-11-27 12:54 UTC, yy0867 requested changes

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Domain/UseCases/Reservation/DefaultCreateReservationDateUseCase.swift
> +            if let newDate = self.calendar.date(byAdding: .minute, value: -((number + 1) * 30), to: newDate) {
매직 넘버에 대한 처리가 있으면 좋을 것 같습니다!

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Domain/UseCases/Reservation/Protocols/CreateReservationDateUseCase.swift
> +    func selectedEndDate(startDate: ReservationDate, endDate: ReservationDate) -> ReservationDate?
createReservationDateUseCase에 selected가 들어가 있는 것이 조금 어색해 보입니다..!

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Presenter/Common/Reusable/TrinapMutiSelectionCalendarView.swift
> +final class TrinapMutiSelectionCalendarView: BaseView {
```suggestion
final class TrinapMultiSelectionCalendarView: BaseView {
```

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Presenter/Common/Reusable/TrinapMutiSelectionCalendarView.swift
> +        calendar.locale = Locale(identifier: "ko_KR")
Locale에는 `.current`가 없나요..?!

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Presenter/Common/Reusable/TrinapMutiSelectionCalendarView.swift
> +        }
filter을 하나로 합치는건 어떨까요?

하나의 filter마다 O(n)이 소요될텐데, 한 번 돌 때 모두 처리하는 것이 조금 더 효율적일 것 같습니다!

```suggestion
        return possibleDate.filter { date in
            let year = self.calendar.component(.year, from: date)
            let month = self.calendar.component(.month, from: date)
            let day = self.calendar.component(.day, from: date)

            return (
                self.calendar.component(.year, from: Date()) == year &&
                self.calendar.component(.month, from: Date()) == month &&
                self.calendar.component(.day, from: Date()) <= day
            )
        }
```

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Presenter/Common/Reusable/TrinapSingleSelectionCalendarView.swift
> +        }
이 부분도 하나로 처리되면 좋을 것 같습니다!!

```suggestion
        return possibleDate.filter { date in
            let year = self.calendar.component(.year, from: date)
            let month = self.calendar.component(.month, from: date)
            let day = self.calendar.component(.day, from: date)
            
            return (
                self.calendar.component(.year, from: Date()) == year &&
                self.calendar.component(.month, from: Date()) == month &&
                self.calendar.component(.day, from: Date()) <= day &&
            )
        }
```

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewController.swift
> +                }
각 파라미터에 대한 Observable들을 각각 메서드에서 Operator들을 연결한 뒤, 이 부분에서는 해당 메서드만 호출하면 가독성이 더 좋아질 것 같습니다..!

ex)
```swift
Input(
    a: aa.map {
            ...
        }
        .map {
            ...
        },
    b: bb.map {
            ...
        }
        .flatMap {
            ...
        }
)
```
=>
```swift
Input(
    a: configureAa(),
    b: configureBb()
)

// ...
private func configureAa() -> Observable<A> {
    return aa.map {
                ...
            }
            .map {
                ...
            },
}

private func configureBb() -> Observable<B> {
    return bb.map {
                ...
            }
            .map {
                ...
            },
}
```

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewController.swift
> +            .disposed(by: disposeBag)
Output에 대한 처리도 메서드별로 나누면 좋을 것 같습니다!

혹은 subscribe에 대한 로직만 따로 메서드로 처리해도 좋을 것 같아요

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewController.swift
> +        dataSource = ReservationDateDataSource(
dataSource와의 거리가 멀어서, `self`를 붙여주면 읽기에 더 좋을 것 같습니다!

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewModel.swift
> +            }
각 case별로 메서드를 구성하는 것이 좋을 것 같습니다!

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewModel.swift
> +                return false
합치는 것은 어떠신가요?

```suggestion
                return startDate != nil && endDate != nil
```

2022-11-27 12:54 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/TimeCell.swift
> +            }
isSelected를 파라미터로 갖는 메서드를 만들고,
해당 메서드에서 isSelected를 기준으로 UI를 구성하면 더 좋을 것 같습니다..!

2022-11-27 12:54 UTC, yy0867 commented on Tuist/Dependencies.swift
> +    .remote(url: "https://github.com/airbnb/HorizonCalendar.git", requirement: .branch("master"))
실행 되셨나요..?

```suggestion
    .remote(url: "https://github.com/airbnb/HorizonCalendar.git", requirement: .branch("master")),
```

2022-11-27 12:56 UTC, yy0867 commented on Trinap/Sources/Presenter/Common/Reusable/TrinapMutiSelectionCalendarView.swift
> +        }
혹은 `dateComponents([.year, .month, .day], from: Date())`를 사용하는 것도 좋을 것 같습니다!

2022-11-27 12:57 UTC, yy0867 commented on Trinap/Sources/Presenter/Common/Reusable/TrinapSingleSelectionCalendarView.swift
> +        }
이부분 또한 `dateComponents([.year, .month, .day], from: Date())` 사용해도 좋을 것 같습니다!

2022-11-27 13:08 UTC, chansooo approved these changes
👍슛

2022-11-27 13:08 UTC, chansooo commented on .swiftlint.yml
이 부분은 추가하신 건가요 아니면 다른 분이 빼시고 풀을 안 받아서 다시 추가되는 걸까용?

2022-11-27 13:08 UTC, chansooo commented on Trinap/Sources/Presenter/Common/Reusable/TrinapSingleSelectionCalendarView.swift
> +    /// - Parameter possibleDate: 작가의 영업일
👍👍👍👍👍👍👍

2022-11-27 13:08 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewController.swift
> +                }
input 파라미터가 길어지면 변수로 만들어서 해당 변수를 넣어주는 방식도 좋을 것 같습니당

2022-11-27 13:45 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/Common/Reusable/TrinapMutiSelectionCalendarView.swift
> +        calendar.locale = Locale(identifier: "ko_KR")
저희 앱이 다국어를 지원하지 않는 것 같아서 locale을 한국으로 고정시켰습니다!

2022-11-27 13:49 UTC, ByeongjooYoo commented on Tuist/Dependencies.swift
> +    .remote(url: "https://github.com/airbnb/HorizonCalendar.git", requirement: .branch("master"))
잘 되었던것 같은데.....혹시 쉼표를 안붙이면 에러가 발생하나요..?

2022-11-27 13:50 UTC, ByeongjooYoo commented on .swiftlint.yml
요거는 제가 수정한 부분입니다!
날짜 생성과 관련된 로직을 구현할 때 컴파일 에러를 내더라고요...
어느 부분에서 문제가 되었는지 내일 데일리 미팅에서 공유하겠습니다!

2022-11-28 05:51 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/Common/Reusable/TrinapMutiSelectionCalendarView.swift
> +        }
수정.

2022-11-28 05:51 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/Common/Reusable/TrinapSingleSelectionCalendarView.swift
> +        }
수정.

2022-11-28 05:52 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewController.swift
> +        dataSource = ReservationDateDataSource(
수정.

2022-11-28 05:55 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/TimeCell.swift
> +            }
수정.

2022-11-28 07:30 UTC, yy0867 approved these changes

2022-11-28 07:30 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewController.swift
> +            deselectedDate: self.transformDeselectedItemToInput()
👍

2022-11-28 07:30 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewController.swift
>      private var viewModel: SelectReservationDateViewModel
```suggestion
    private let viewModel: SelectReservationDateViewModel
```

2022-11-28 07:42 UTC, merged