Feature/Edit Possible Date View
boostcampwm-2022/iOS02-Trinap pull request #188
Opened 2022-11-29 07:46 UTC by ByeongjooYoo

# 작업 내용
> 해결한 이슈 넘버와 설명을 적어주세요

- resolved: #54 
- resolved: #68

# 질문 및 특이사항
> 해결하지 못한 부분이나 팀원들에게 알려줄 사항을 적어주세요

EditPossibleDateUseCase가 불필요하다 생각되어 EditPhotographerUseCase와 FetchPhotographerUseCase를 재사용하여 구현하였습니다.

# 체크리스트
- [ ] 빌드가 되는 코드인가요?
- [ ] Warning이 없는 코드인가요?
- [ ] Merge할 브랜치가 올바른가요?
- [ ] 코딩 컨벤션이 올바른가요?

2022-11-29 16:05 UTC, yy0867 requested changes

2022-11-29 16:05 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPossibleDate/EditPossibleDateViewController.swift
> +                }
self 순환 참조입니다..!

```suggestion
                .withUnretained(self) { owner, _ in
                    return owner.trinapCalenderView.possibleDate.value
                }
```

2022-11-29 16:05 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPossibleDate/EditPossibleDateViewController.swift
> +    }
```swift
editDoneButton.setTitleColor(TrinapAsset.primary.color, for: .normal)
editDoneButton.setTitleColor(TrinapAsset.disabled.color, for: .disabled)
```
로 설정해놓는게 더 좋을 것 같습니다!

2022-11-29 16:21 UTC, d0yvn approved these changes

2022-11-29 16:21 UTC, d0yvn commented on Trinap/Sources/Data/Repositories/Photograhper/DefaultPhotograhperRepository.swift
> +
👍🏻

2022-11-29 16:21 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPossibleDate/EditPossibleDateViewController.swift
> +
ViewDidLoad에 새로운 메소드를 호출하지 않는다면 생략해도 된다고 생각합니다!

2022-11-29 16:21 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPossibleDate/EditPossibleDateViewController.swift
> +                }
editButtonTap의 변수명을 봤을땐 버튼 탭만 input으로 넣는 것으로 보이는데 mapping으로 한번에 처리하기보다는 input에 button동작과 possibleDate를 함께 넘겨서 viewModel에서 처리하는게 더 좋아보입니다!

2022-11-29 17:08 UTC, chansooo approved these changes

2022-11-29 17:08 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPossibleDate/EditPossibleDateViewController.swift
> +    }
다른 로직 처리 없이 popViewController만 해주면 된다면 viewmodel에서 coordinator를 통해서 pop해줘도 되지 않을까요?

2022-11-29 17:08 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPossibleDate/EditPossibleDateViewModel.swift
> +                }
error로 넘겨주게 되면 에러가 발생하면 뷰컨에서 onNext가 호출이 되지 않아서 popViewController가 호출이 되지 않을 것 같습니다.

2022-11-30 01:54 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPossibleDate/EditPossibleDateViewModel.swift
> +                }
`owner.photographer`가 nil이면 작가의 영업일을 업데이트를 해주지 못하기 때문에 해당 로직은 실패라고 생각했습니다!
그래서  `popViewController`는` owner.photographer가 nil이 아닐때`만  호출 되도록 구현하였습니다!

2022-12-01 01:07 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPossibleDate/EditPossibleDateViewController.swift
> +            self.editDoneButton.setTitleColor(TrinapAsset.disabled.color, for: .disabled)
음... 그 버튼을 생성할 때
```swift
let editDoneButton = UIButton().than {
    ...
    $0.setTitleColor(TrinapAsset.primary.color, for: .normal)
    $0.setTitleColor(TrinapAsset.disabled.color, for: .disabled)
    ...
}
```

이렇게 하고 
현재 메서드 안에서 `editDoneButton.isEnabled = isEnabled`만 설정하면 좋을 것 같다는 이야기였습니다... ㅋㅋㅋ

2022-12-01 01:07 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPossibleDate/EditPossibleDateViewController.swift
> +                    return owner.trinapCalenderView.possibleDate.value
👍

2022-12-01 01:08 UTC, yy0867 approved these changes

2022-12-01 01:10 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPossibleDate/EditPossibleDateViewController.swift
> +            self.editDoneButton.setTitleColor(TrinapAsset.disabled.color, for: .disabled)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 수정해오겠습니당~!

2022-12-01 01:11 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPossibleDate/EditPossibleDateViewController.swift
> +            self.editDoneButton.setTitleColor(TrinapAsset.disabled.color, for: .disabled)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
조금 더 자세하게 말씀드렸어야 했는데 죄성합니다...

2022-12-01 01:45 UTC, merged