Feature/photographer detail view
boostcampwm-2022/iOS02-Trinap pull request #190
Opened 2022-11-29 16:49 UTC by chansooo

# 작업 내용
> 해결한 이슈 넘버와 설명을 적어주세요

resolved: 
- photographerDetail 뷰컨 기본적인 와꾸 잡기
- 뷰모델 데이터 뿌려주는 부분 구현

# 질문 및 특이사항
> 해결하지 못한 부분이나 팀원들에게 알려줄 사항을 적어주세요

# 체크리스트
- [ ] 빌드가 되는 코드인가요?
- [ ] Warning이 없는 코드인가요?
- [ ] Merge할 브랜치가 올바른가요?
- [ ] 코딩 컨벤션이 올바른가요?

2022-11-29 17:04 UTC, yy0867 commented
와꾸 잡기 ㅋㅋㅋㅋㅋㅋㅋ

2022-11-29 17:16 UTC, yy0867 requested changes

2022-11-29 17:16 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/CollectionView/PhotographerProfileCell.swift
> +        self.addSubviews([profileImage, nickNameLabel, locationLabel, filterView])
collectionViewCell이면 contentView에 addSubview 해주어야 할 것 같습니당
```suggestion
        self.contentView.addSubviews([profileImage, nickNameLabel, locationLabel, filterView])
```

2022-11-29 17:16 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewController.swift
> +        }
이거 작성 안해줄 경우 `nil`로 설정이 안되는지 궁금합니다..!

2022-11-29 17:16 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewController.swift
> +                return cell
동작이 중복되는데, 제네릭으로 함수를 작성해서 재사용할 수 없을까요,,?

2022-11-29 17:16 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewController.swift
> +        let isEditable = false
메서드 내부에서 사용되지 않는 것 같은데 제거해도 될 것 같습니다!

2022-11-29 17:17 UTC, yy0867 commented
일단은 contentView만 확인해주시면 될 것 같습니다!

2022-11-29 17:18 UTC, yy0867 requested changes

2022-11-29 17:18 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Search/SearchViewController.swift
>          $0.setImage(UIImage(named: "icSearchNonW"), for: UISearchBar.Icon.search, state: .normal)
혹시 저번 PR에 말씀드린 내용은 사용하지 않으신 걸까요?

2022-11-30 03:07 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewController.swift
> +        }
넵 안되고 오류가 뜨더라구요,,

2022-11-30 03:07 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewController.swift
> +                return cell
도윤님 코드에서 사용하는 부분만 그대로 사용 중인데 전부 동작되도록 만들고 바꿔두도록 하겠습니다

2022-11-30 03:09 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Search/SearchViewController.swift
>          $0.setImage(UIImage(named: "icSearchNonW"), for: UISearchBar.Icon.search, state: .normal)
TrinapAsset에 따로 없고, systemImage여서 그냥 이렇게 사용했습니다

2022-11-30 04:47 UTC, d0yvn approved these changes

2022-11-30 04:47 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewController.swift
> +        }
reusableView 사용하지 않으면 아예 선언해주지 않으면 되지 않을까요!?

2022-11-30 04:47 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewController.swift
> +        }
collectionView.register할 때 Cell부분만 등록하니까 해당 코드가 없어도 될 것 같습니다!

2022-11-30 04:47 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/MyPage/Photographer/EditPhotographerViewModel.swift
> +                }
👍🏻

2022-12-01 00:58 UTC, ByeongjooYoo approved these changes

2022-12-01 01:15 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Search/SearchViewController.swift
>          $0.setImage(UIImage(named: "icSearchNonW"), for: UISearchBar.Icon.search, state: .normal)
아 그렇군요..!
그런데 혹시 SearchBar 사용할 때 돋보기 그림이 기본으로 되어 있지 않나요..?
따로 이미지를 사용하신 이유가 궁금합니닷

2022-12-01 01:15 UTC, yy0867 approved these changes

2022-12-01 01:25 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Search/SearchViewController.swift
>          $0.setImage(UIImage(named: "icSearchNonW"), for: UISearchBar.Icon.search, state: .normal)
기본으로 넣었을 때 좌측에 돋보기 버튼이 따로 없어서 추가해주었습니다! 
setImage의 첫번째 인자에 image를 nil로 주어도 아이콘을 지정해줘서 들어가길래 nil로 처리하고 넣어줬습니다 :)

2022-12-01 01:27 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewController.swift
> +        }
오잉 새로 확인해보니까 없어도 됩니다..! ㅋㅋㅋ 삭제하겠습니다

2022-12-01 01:27 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewController.swift
> +        }
엇 반영했습니다!

2022-12-01 01:28 UTC, merged