Feature/SignOut, DropOut 구현
boostcampwm-2022/iOS02-Trinap pull request #194
Opened 2022-12-01 12:02 UTC by ByeongjooYoo

# 작업 내용
> 해결한 이슈 넘버와 설명을 적어주세요
로그아웃, 회원탈퇴 구현했습니다.
resolved: 

# 질문 및 특이사항
> 해결하지 못한 부분이나 팀원들에게 알려줄 사항을 적어주세요

# 체크리스트
- [ ] 빌드가 되는 코드인가요?
- [ ] Warning이 없는 코드인가요?
- [ ] Merge할 브랜치가 올바른가요?
- [ ] 코딩 컨벤션이 올바른가요?

2022-12-01 12:14 UTC, chansooo approved these changes

2022-12-01 12:14 UTC, chansooo commented on Trinap/Sources/Domain/UseCases/Auth/DropOut/DefaultDropOutUseCase.swift
> +    }
flatMap 하나로 줄일 수 있지 않을까요?

2022-12-01 12:14 UTC, chansooo commented on Trinap/Sources/Domain/UseCases/Auth/SignOut/DefaultSignOutUseCase.swift
> +            .catchAndReturn(false)
catchAndReturn을 하면 stream이 끊기지 않나요?

2022-12-01 12:44 UTC, yy0867 commented
오토사인인 고쳐와
요

2022-12-01 13:06 UTC, yy0867 requested changes
오토사인인 고쳐와
요

2022-12-01 13:06 UTC, yy0867 commented on Trinap/Sources/Data/Repositories/Auth/DefaultAuthRepository.swift
> +        self.tokenManager.deleteToken(with: .fcmToken)
이 둘도 삭제에 성공/실패 여부가 반환값으로 나오는데, `error` 조건에 반영하면 더 좋을 것 같습니다!

2022-12-01 13:06 UTC, yy0867 commented on Trinap/Sources/Domain/UseCases/Auth/DropOut/DefaultDropOutUseCase.swift
> +            }
`zip`을 사용하면 독립적인 작업들을 한번에 비동기로 처리할 수 있을 것 같습니닷

2022-12-01 13:06 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewModel.swift
> +        //            .disposed(by: disposeBag)
```suggestion
```

2022-12-01 13:06 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/DropOut/DropOutViewController.swift
> +            .disposed(by: disposeBag)
`agreeDropOutButton.rx.tap` 이벤트를 `share`로 처리하면 더 안전할 것 같습니다!

혹은 `do` 사용해서 로직 두개를 합쳐도 좋을 것 같습니당

2022-12-05 07:16 UTC, d0yvn approved these changes

2022-12-05 07:16 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/MyPage/DropOut/DropOutViewModel.swift
> +    }
개인적으로 이러한 로직은 ViewModelType정의를 안해도 된다고 생각합니다!

2022-12-05 07:16 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewController.swift
> +                } else {
dismiss는 coordinator를 사용하지 않아도 괜찮은건가요?

2022-12-05 07:19 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/Main/SelectReservationDate/SelectReservationDateViewController.swift
> +                } else {
Present된 ViewController라 coordinator에서 해당 ViewController에 대한 참조를 가지지 않게 하기 위해서 ViewController에서 직접 Dismiss해주었어요!

2022-12-05 07:21 UTC, yy0867 approved these changes
👍

2022-12-05 07:21 UTC, merged