Feature/photographer detail view
boostcampwm-2022/iOS02-Trinap pull request #205
Opened 2022-12-05 15:33 UTC by chansooo

# 작업 내용
> 해결한 이슈 넘버와 설명을 적어주세요

- 확인 버튼 눌렀을 때 로직 구성 중입니다.
- 현재 reservation 만들기, chatRoom 만들기, chat 보내기까지 완료했습니다.

- chatRoom 확인해서 user와 phortographer가 사용하는 chatroom이 있으면 해당 chatroom에 예약 문자 던져주도록 하는 로직이 추가되어야합니다. (완료)

resolved: 

# 질문 및 특이사항
> 해결하지 못한 부분이나 팀원들에게 알려줄 사항을 적어주세요

- chat 보낸 후 coordinator에서 chatroomView로 전환해줘야하는데 해당 부분 고민중입니다.
- chatDetailView처럼 다른 coordinator에서 접근할 수 있는 뷰의 경우 init에서 coordinator의 타입을 ChatCoordinator로 고정시키면 안될 것 같아서 해당 부분 이야기해봐야할 것 같습니다.

# 체크리스트
- [x] 빌드가 되는 코드인가요?
- [ ] Warning이 없는 코드인가요?
- [x] Merge할 브랜치가 올바른가요?
- [x] 코딩 컨벤션이 올바른가요?

2022-12-06 02:27 UTC, yy0867 requested changes
죄송합니다.....ㅠㅠ

2022-12-06 02:27 UTC, yy0867 commented on Trinap/Sources/Domain/UseCases/Chat/DefaultCreateChatroomUseCase.swift
> +                $0.filter { $0.photographerUserId == photographerUserId || $0.customerUserId == photographerUserId }
이 `filter`는 어떤 로직인가요?

2022-12-06 02:27 UTC, yy0867 commented on Trinap/Sources/Domain/UseCases/Chat/DefaultSendFirstChatUseCase.swift
> +            content: "",
아 그 음... 죄송합니다 우선...

chatType이 reservation이면 content가 reservationId가 되어야 할 것 같습니다...
그래야 채팅 클릭 시 reservationId를 사용해서 ReservationDetail을 구성할 수가 있어가지고....

죄송합니다...

2022-12-06 05:53 UTC, chansooo commented on Trinap/Sources/Domain/UseCases/Chat/DefaultSendFirstChatUseCase.swift
> +            content: "",
@yy0867 변경했으니 확인해주세요~

2022-12-06 06:22 UTC, yy0867 approved these changes
👍

2022-12-06 13:35 UTC, ByeongjooYoo approved these changes

2022-12-06 16:49 UTC, d0yvn approved these changes

2022-12-06 16:49 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewModel.swift
> +            .flatMap { $0.0.showAlert() }
$0.0 의미가 궁금합니다

2022-12-06 16:49 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewModel.swift
> +            .filter { $0 }
filter가 없어도 될 것 같은데 어떤 용도인가요?

2022-12-06 16:49 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewModel.swift
> +                Logger.print(111)
????

2022-12-06 16:49 UTC, d0yvn commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewModel.swift
> +
에러로 따로 처리하는게 좋을 것 같습니당

2022-12-07 01:19 UTC, merged

2022-12-07 01:20 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewModel.swift
> +                Logger.print(111)
네?

2022-12-07 01:20 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewModel.swift
> +            .filter { $0 }
showAlert에서 확인 취소로 Bool 값이 넘어오는데 false일 때 끊어주기 ㄷ위함입니다

2022-12-07 01:21 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewModel.swift
> +            .flatMap { $0.0.showAlert() }
$0이 (viewModel, void)여서 $0.0으로 했습니다.

2022-12-07 01:21 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewModel.swift
> +
아아 넵넵

2022-12-07 01:52 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewModel.swift
> +            .flatMap { $0.0.showAlert() }
``` swift
.flatMap { something in
let (viewModel, _ ) = something
viewModel.showAlert() 
}
```
요런식으로 수정하면 `$0.0`의 의미가 명확해질 것 같습니다!