Feature/blocklist view 구현 + Custom NavigationBar 구현
boostcampwm-2022/iOS02-Trinap pull request #213
Opened 2022-12-07 16:04 UTC by ByeongjooYoo

# 작업 내용
> 해결한 이슈 넘버와 설명을 적어주세요

- resolved: #176, #55, #69, #103, #84, #212

# 질문 및 특이사항
> 해결하지 못한 부분이나 팀원들에게 알려줄 사항을 적어주세요
MyPage에서 작가 프로필 설정, 문의하기 화면 제외 navigationBar 수정 해두었습니다.
# 체크리스트
- [ ] 빌드가 되는 코드인가요?
- [ ] Warning이 없는 코드인가요?
- [ ] Merge할 브랜치가 올바른가요?
- [ ] 코딩 컨벤션이 올바른가요?

2022-12-07 17:21 UTC, chansooo approved these changes

2022-12-07 17:21 UTC, chansooo commented on Trinap/Sources/Data/Repositories/Block/DefaultBlockRepository.swift
> +    }
blockId를 받아서 생성하는 것을 보니 수정하는 메소드인 것 같은데 update를 사용하는 것이 좋지 않을까요?

2022-12-07 17:21 UTC, chansooo commented on Trinap/Sources/Domain/UseCases/Block/DefaultFetchBlockUsersUseCase.swift
> +        }
where 사용해서 인덴트 줄이는 방법이 있을 것 같습니다.

2022-12-07 17:21 UTC, chansooo commented on Trinap/Sources/Presenter/Common/Reusable/TrinapNavigationBarView.swift
> +    // MARK: - UI
👍

2022-12-07 17:29 UTC, chansooo approved these changes

2022-12-07 17:29 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/MyPage/BlockList/BlockListViewModel.swift
> +            .disposed(by: disposeBag)
두 로직을 따로 둬야할까요? 
`fetchBlockUseCase.execute(blockId: String, flag: Bool)`과 같은 아이를 만들어서 flag가 false면 삭제, true면 추가하도록 하면 어떨까요?

그리고 현재 뷰가 뷰에서 나갈 때 업데이트 되는 로직인데 실시간으로 삭제, 생성을 하면 코스트를 많이 쓰는 작업이 아닐가 하는 생각이 듭니다

2022-12-07 17:38 UTC, yy0867 requested changes
bloecked 오타난 것 수정해주시면 감사하겠습니다..!

2022-12-07 17:38 UTC, yy0867 commented on Trinap/Sources/Domain/Repositories/Block/BlockRepository.swift
> +    func blockUser(blockedUserId: String, blockId: String) -> Single<Void>
두 개는 어떤게 다른건가요..!

2022-12-07 17:38 UTC, yy0867 commented on Trinap/Sources/Domain/UseCases/Block/DefaultFetchBlockUsersUseCase.swift
>          return blockRepository.fetchBlockedUser()
`blockRepository.fetchBlockedUser()`라는 이름만 보면, 반환값이 `Block.BlockedUser` 혹은 `[Block.BlockedUser]`인 것으로 착각하기 쉬울 것 같습니다!

2022-12-07 17:38 UTC, yy0867 commented on Trinap/Sources/Domain/UseCases/Block/DefaultFetchBlockUsersUseCase.swift
> +                let (blocks, bloeckedUserIds) = blockedInfo
```suggestion
                let (blocks, blockedUserIds) = blockedInfo
```

2022-12-07 17:38 UTC, yy0867 commented on Trinap/Sources/Domain/UseCases/Block/DefaultFetchBlockUsersUseCase.swift
> +                return owner.userRepository.fetchUsers(userIds: bloeckedUserIds)
```suggestion
                return owner.userRepository.fetchUsers(userIds: blockedUserIds)
```

2022-12-07 17:38 UTC, yy0867 commented on Trinap/Sources/Domain/UseCases/Block/Protocols/FetchBlockUsersUseCase.swift
> +    func fetchBlockUsers() -> Observable<[Block.BlockedUser]>
이 UseCase 이름과 메서드 이름이 `fetchBlockedUsers`면 더 이해하기 쉬울 것 같습니다!

2022-12-07 17:38 UTC, yy0867 commented on Trinap/Sources/Presenter/Common/Reusable/TrinapNavigationBarView.swift
> +final class TrinapNavigationBarView: BaseView {
저도 몇 부분에서 이렇게 사용 중이지만 NavigationBar를 이렇게 사용해도 될지 계속 고민이 됩니다...

- NavigationBar만 사용할 수 있는 기능 혹은 Bar에서 사용하기 쉽지만 직접 구현하기 어려운 부분이나
- top safeArea를 사용할 수 없거나
- scroll시 Shadow를 설정해주는 부분
- 어느 곳에서는 NavigationBar에 맞춰 구현하고, 어느 곳에서는 TrinapNavigationBarView에 맞춰서 구현했을 때 서로 이어 주어야 할 일이 생긴다면 발생하는 문제

(우선 시간이 없으니...) 나중에 이 부분도 같이 이야기 해 보면 좋을 것 같습니다..! 👍

2022-12-07 17:38 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/BlockList/BlockListCell.swift
> +            self.blockStatusButton.isSelected.toggle()
`self.blockStatusButton.isSelected = self.isBlockStatusButtonSelected`가 더 정확할 것 같습니다..!

2022-12-07 17:38 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/BlockList/BlockListCell.swift
> +    var isBlockStatusButtonSelected = false {
rx를 사용하지 않고 해당 변수와 프로퍼티 옵저버를 사용하신 이유가 있을까요?

2022-12-07 17:38 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/BlockList/BlockListViewController.swift
> +    typealias Snapshot = NSDiffableDataSourceSnapshot<Section, Block.BlockedUser>
혹시 이 부분까지 `BlockedUser`가 가져와지게 되면, `Block` 모델은 사용되는 곳이 없나요..?

BlockedUser가 Mapper고 Block이 모델이라면 Block 안에 User가 들어 있는 것이 더 적절하지 않을까 생각합니다..!

2022-12-07 17:38 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/BlockList/BlockListViewModel.swift
> +            .disposed(by: disposeBag)
함수로 분할하면 더 좋을 것 같습니다..!

2022-12-07 17:38 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/MyPage/EditProfile/EditProfileViewController.swift
> +    private let imagePicker = ImagePickerController()
```suggestion
    private lazy var imagePicker = ImagePickerController()
```

2022-12-08 06:21 UTC, ByeongjooYoo commented on Trinap/Sources/Data/Repositories/Block/DefaultBlockRepository.swift
> +    }
차단 해제를 했다가 취소한 경우 동일한 blockId로 서버에 추가해주는 메소드입니다!
현재 유저가 차단 해제를 하면 즉시 서버에서 해당 block 정보를 지우고 차단 해제를 취소하면 다시 생성하는 로직으로 구현되어 있어 이전과 동일한 blockId로 block 정보를 생성하는 함수가 필요해서 구현했습니다!

2022-12-08 06:24 UTC, ByeongjooYoo commented on Trinap/Sources/Domain/Repositories/Block/BlockRepository.swift
> +    func blockUser(blockedUserId: String, blockId: String) -> Single<Void>
`func blockUser(blockedUserId: String) -> Single<Void>`는 특정 유저를 차단할 때 사용되는 메서드입니다.
`func blockUser(blockedUserId: String, blockId: String) -> Single<Void>`는 `차단해제를` 했다가 `차단해제`를 취소한 경우 동일한 blockId로 Block 정보를 생성해줘야 해서 추가한 메서드입니다!

2022-12-08 06:27 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/MyPage/BlockList/BlockListViewModel.swift
> +            .disposed(by: disposeBag)
```
두 로직을 따로 둬야할까요?
fetchBlockUseCase.execute(blockId: String, flag: Bool)과 같은 아이를 만들어서 flag가 false면 삭제, true면 추가하도록 하면 어떨까요?
```
-> 수정해서 반영했습니다!
`
그리고 현재 뷰가 뷰에서 나갈 때 업데이트 되는 로직인데 실시간으로 삭제, 생성을 하면 코스트를 많이 쓰는 작업이 아닐가 하는 생각이 듭니다`
-> 저도 이 처리에 대해서 고민을 해보았는데 저 화면에서 비정상적으로 종료되는 경우(배터리 부족으로 휴대폰이 꺼지는 경우 등등)을 생각 해보았을 때 실시간으로 업데이트 시켜주는 것이 안전하다고 생각되었습니다.
그리고 이미지처럼 무거운 데이터가 전송되는 것이 아니여서... 저 정도 코스트는 괜찮지...않을까..?라는 개인적인 생각입니다.....

2022-12-08 06:34 UTC, ByeongjooYoo commented on Trinap/Sources/Presenter/TabBar/MyPage/BlockList/BlockListCell.swift
> +    var isBlockStatusButtonSelected = false {
rx 사용이 미숙....해서..?

2022-12-08 06:35 UTC, merged