Feature/photographer detail view
boostcampwm-2022/iOS02-Trinap pull request #215
Opened 2022-12-07 17:07 UTC by chansooo

# 작업 내용
> 해결한 이슈 넘버와 설명을 적어주세요

resolved: 
- photographerDetailCoordinator 생성
- 신고하기, 차단하기 구현

# 질문 및 특이사항
> 해결하지 못한 부분이나 팀원들에게 알려줄 사항을 적어주세요

- 신고하기 간단하게 구현해버렸습니다... 이렇게 하고 추가적으로 나중에 수정,.,,, 하겠습니다.,..
- 디테일뷰에서 채팅 넘어가는 부분 detailChatCoordinator 구현되면 연결하겠습니다.
# 체크리스트
- [x] 빌드가 되는 코드인가요?
- [ ] Warning이 없는 코드인가요?
- [x] Merge할 브랜치가 올바른가요?
- [x] 코딩 컨벤션이 올바른가요?

2022-12-07 17:48 UTC, yy0867 commented
829줄... 설레는군요

2022-12-07 18:12 UTC, yy0867 requested changes
DI Container부분 한번만 봐주시면 감사하겠습니다 !

2022-12-07 18:12 UTC, yy0867 commented on Trinap/Sources/Domain/Repositories/Sue/SueRepository.swift
> +    func fetchSuedUser() -> Single<[Sue]>
`fetchSuedUser`이면 반환값이 `User`이거나 `[User]`일 것으로 예상될 것 같습니다..!

2022-12-07 18:12 UTC, yy0867 commented on Trinap/Sources/Domain/UseCases/Sue/DefaultCreateSueUseCase.swift
> +        }
```suggestion
        let rawContents = contents.contents
```
이거는 안될까요..?

아래 코드에서 contents면 바로 String을 반환하는 것 같아서 여쭤봅니다!

https://github.com/boostcampwm-2022/iOS02-Trinap/blob/2eebf7100530ac6adab91fb6a759e8797d009528/Trinap/Sources/Domain/Models/Sue.swift#L51-L62

2022-12-07 18:12 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/Coordinator/MainCoordinator.swift
> +        }
self.childCoordinators에서 제거 안해도 괜찮을까요..?
이 부분 고민하다가 
그냥 pop 돼버리면 `didFinish`가 호출 안돼서
일단 그냥 올리긴 했습니다 ㅋㅋㅋㅋ

2022-12-07 18:12 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/Coordinator/PhotographerDetailCoordinator.swift
> +        Logger.print("가드안걸림")
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-12-07 18:12 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/Coordinator/PhotographerDetailDependencyContainer.swift
> +    let chatRepository: ChatRepository
여기서 많은 레포지토리들이 재사용이 안되는 것 같은데,
재사용이 안된다면 오히려 DI Container에서 잡고 있는게 독이 될 수 있을 것 같습니다!

하나의 UseCase에서만 사용되면 해당 UseCase make함수에서 생성하는 것이 좋다고 생각합니닷

2022-12-07 18:12 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewController.swift
> +                alert.addAction(title: "확인", style: .primary) { }
아래 커밋에 `completion: (() -> Void)? = nil`가 있는 것 같은데 수정하면 좋을 것 같습니다!

2022-12-07 18:12 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/Sue/SueViewModel.swift
> +                }
함수로 빼는게 좋을 것 같습니다!

2022-12-08 01:22 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Main/PhotographerDetail/PhotographerDetailViewController.swift
> +                alert.addAction(title: "확인", style: .primary) { }
wow

2022-12-08 01:23 UTC, chansooo commented on Trinap/Sources/Presenter/TabBar/Main/Coordinator/PhotographerDetailDependencyContainer.swift
> +    let chatRepository: ChatRepository
통일성을 주는 것보다 그렇게 하는 것이 나을까요?

2022-12-08 02:15 UTC, yy0867 commented on Trinap/Sources/Presenter/TabBar/Main/Coordinator/PhotographerDetailDependencyContainer.swift
> +    let chatRepository: ChatRepository
저는 메모리에 안남겨놔도 되는 것들은 안남겨놓는게 좋다고 생각합니다..!

근데 다른사람들은 어떻게 쓰는지 몰라서 일단 찬수님 하시고싶은대로 하셔도 될 것ㄱ ㅏㅌㅇ스비낟

2022-12-08 02:16 UTC, yy0867 approved these changes
jjjass

2022-12-08 02:16 UTC, ByeongjooYoo approved these changes
👍

2022-12-08 03:04 UTC, merged